env:
  matrix:
  - BUNDLER_VERSION=2.2.15
language: ruby
cache: bundler
rvm:
- 3.0.1
services:
- docker
before_install:
- gem install bundler -v $BUNDLER_VERSION
bundler_args: "--jobs=3 --retry=3"

jobs:
  include:
    - stage: test
      name: RSpec
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
      script:
        - bundle exec rspec lib
      after_script:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    - stage: test
      name: Lint
      script:
        - bundle exec standardrb

