FROM ruby:3.0.2

ARG TRAVIS_TEST_RESULT
ARG CC_TEST_REPORTER_ID

WORKDIR /app

RUN curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
RUN chmod +x ./cc-test-reporter
RUN ./cc-test-reporter before-build

ADD Gemfile Gemfile.lock /app/
RUN bundle install --jobs=3 --retry=3


ADD . /app/

RUN bundle exec rspec lib
RUN bundle exec standardrb


RUN ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
